# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_db(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(630, 400)
        MainWindow.setWindowTitle('ПОМОЩНИК по ПОГОДЕ')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 610, 350))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.place_to_edit_text = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.place_to_edit_text.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.place_to_edit_text)
        self.searchPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.searchPushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.searchPushButton)
        self.Button_to_go_back = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_to_go_back.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.Button_to_go_back)
        self.place_to_print_data = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.place_to_print_data.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.place_to_print_data)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 326, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchPushButton.setText(_translate("MainWindow", "Найти"))
        self.Button_to_go_back.setText(_translate("MainWindow", "Назад"))
