# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(630, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setSizeIncrement(QtCore.QSize(5, 5))
        MainWindow.setStyleSheet(
            "#MainWindow{border-image:url(assets/1620034384_12-phonoteka_org-p-svetlii-fon-s-zheltimi-tsvetami-14.jpg)}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 60, 258, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_start = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_start.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton_start, 1, 0, 1, 1)
        self.exit_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.exit_pushButton.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.exit_pushButton, 3, 0, 1, 1)
        self.search_in_database_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.search_in_database_pushButton.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.search_in_database_pushButton, 2, 0, 1, 1)
        self.label_to_send_text = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_to_send_text.setFont(font)
        self.label_to_send_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_to_send_text.setObjectName("label")
        self.gridLayout.addWidget(self.label_to_send_text, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 389, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ПОМОЩНИК по ПОГОДЕ"))
        self.pushButton_start.setText(_translate("MainWindow", "СТАРТ"))
        self.exit_pushButton.setText(_translate("MainWindow", "Выход"))
        self.search_in_database_pushButton.setText(_translate("MainWindow", 'Поиск в базе данных'))
        self.label_to_send_text.setText(_translate("MainWindow", "ПОМОЩНИК по ПОГОДЕ"))
