# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(630, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setBaseSize(QtCore.QSize(630, 400))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(400, 30, 200, 200))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.place_to_send_cityName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.place_to_send_cityName.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.place_to_send_cityName)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(400, 10, 180, 20))
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 350, 350))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 1)
        self.send_push_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.send_push_button.setObjectName('send_push_button')
        self.send_push_button.setGeometry(40, 45, 200, 200)
        self.verticalLayout.addWidget(self.send_push_button)
        self.push_button_go_back = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.push_button_go_back.setObjectName('push_button_go_back')
        self.push_button_go_back.setGeometry(60, 60, 200, 200)
        self.verticalLayout.addWidget(self.push_button_go_back)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ПОМОЩНИК по ПОГОДЕ"))
        self.label.setText(_translate("Form", "Введите имя города:"))
        self.send_push_button.setText(_translate("Form", 'Отправить'))
        self.push_button_go_back.setText(_translate("Form", 'На главную'))
